//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.23 at 09:55:37 AM BST 
//


package com.narayanjoshi.simplesoapserverapp.gs_ws;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.narayanjoshi.simplesoapserverapp.gs_ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.narayanjoshi.simplesoapserverapp.gs_ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddRequest }
     * 
     */
    public AddRequest createAddRequest() {
        return new AddRequest();
    }

    /**
     * Create an instance of {@link RequestOperand }
     * 
     */
    public RequestOperand createRequestOperand() {
        return new RequestOperand();
    }

    /**
     * Create an instance of {@link SubtractRequest }
     * 
     */
    public SubtractRequest createSubtractRequest() {
        return new SubtractRequest();
    }

    /**
     * Create an instance of {@link DivideRequest }
     * 
     */
    public DivideRequest createDivideRequest() {
        return new DivideRequest();
    }

    /**
     * Create an instance of {@link MultipleRequest }
     * 
     */
    public MultipleRequest createMultipleRequest() {
        return new MultipleRequest();
    }

    /**
     * Create an instance of {@link ResponseResult }
     * 
     */
    public ResponseResult createResponseResult() {
        return new ResponseResult();
    }

    /**
     * Create an instance of {@link RegisterRequest }
     * 
     */
    public RegisterRequest createRegisterRequest() {
        return new RegisterRequest();
    }

    /**
     * Create an instance of {@link RequestCredential }
     * 
     */
    public RequestCredential createRequestCredential() {
        return new RequestCredential();
    }

    /**
     * Create an instance of {@link AuthenticateRequest }
     * 
     */
    public AuthenticateRequest createAuthenticateRequest() {
        return new AuthenticateRequest();
    }

    /**
     * Create an instance of {@link WhoamiRequest }
     * 
     */
    public WhoamiRequest createWhoamiRequest() {
        return new WhoamiRequest();
    }

    /**
     * Create an instance of {@link ResponseProfile }
     * 
     */
    public ResponseProfile createResponseProfile() {
        return new ResponseProfile();
    }

    /**
     * Create an instance of {@link UpdateProfileRequest }
     * 
     */
    public UpdateProfileRequest createUpdateProfileRequest() {
        return new UpdateProfileRequest();
    }

    /**
     * Create an instance of {@link UploadProfilePictureRequest }
     * 
     */
    public UploadProfilePictureRequest createUploadProfilePictureRequest() {
        return new UploadProfilePictureRequest();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     * 
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

}
