//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.23 at 09:55:37 AM BST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "com.narayanjoshi.simplesoapserverapp.gs_ws", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.narayanjoshi.simplesoapserverapp.gs_ws;
